### ISSUE TITLE
Help with running ollama (local LLM) with NPU on Fedora

### ISSUE THREAD

**Issue by mecattaf** [xanderlent/intel-npu-driver-rpm#4]
Hi Xander,

First off thank you for much for your [Copr repo](https://copr.fedorainfracloud.org/coprs/xanderlent/intel-npu-driver).
Like you, I have a laptop with NPU (in my case  Ultra 9 Processor 185H) and I run Fedora as my OS. I am excited to leverage NPU acceleration for running locally hosted LLMs through Ollama.  I was very disappointed to see that intel only supports Ubuntu. 

Intel provides [the following guide](https://www.intel.com/content/www/us/en/content-details/826081/running-ollama-with-open-webui-on-intel-hardware-platform.html) to run Ollama with NPU acceleration. Specifically:

1) Installing GPU Driver (your repo is a key part of this). They provide this [ubuntu-specific script](https://github.com/intel/edge-developer-kit-reference-scripts/blob/main/gpu/arc/dg2/setup.sh)

2)  Install oneAPI base toolkit. For this we can just create `oneAPI.repo` in yum.repos.d like so:
```
[oneAPI]
name=Intel® oneAPI repository
baseurl=https://yum.repos.intel.com/oneapi
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://yum.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
```
3) Make sure python 3.11 is installed (we have 3.12 with fedora so good to go here).

4) Installing IPEX LLM:
```
$ python3.11 -m venv llm_env
$ source llm_env/bin/activate
$ pip install --pre --upgrade ipex-llm[cpp]
$ mkdir llama-cpp
$ cd llama-cpp
$ init-ollama
```

5) Run Ollama Serve with Intel GPU:
```
$ export OLLAMA_NUM_GPU=999
$ export no_proxy=localhost,127.0.0.1
$ export ZES_ENABLE_SYSMAN=1
$ source /opt/intel/oneapi/setvars.sh
$ export SYCL_CACHE_PERSISTENT=1
$ ./ollama serve
```

I seem to be having problems with step 1. Were you able to run Ollama with NPU acceleration? If yes, can you provide me with the list of packages you installed along with `intel-npu-level-zero` to get it to work?

Finally, I would be keen to provide a guide on how to use NPU-accelerated Ollama for less technical users like myself. I am aware of a [snap](https://github.com/canonical/intel-npu-driver-snap/tree/main) being available but there has to be a better way for Fedora...

Yours,
T

**Comment by xanderlent** [comment]
Hello Thomas,

First, thank you for using the package and for providing feedback!

Second, while investigating the software stack you describe, I was blown away by the ease-of-use of Ollama, Open WebUI, etc. I had no idea that the AI/ML community had built such impressive open-source tools in the past few years.

Third, I have not yet tried to get any of the high-level tech on this stack working; I have mostly spent time poking directly at the Level Zero API. When I looked at packaging the [Intel NPU Acceleration Library](https://github.com/intel/intel-npu-acceleration-library), it seems to use the driver only indirectly through OpenVINO as well as having a number of Python dependencies that would also need packaging. I do hope to get around to packaging that and other upstream tools soon...

Fourth, I investigated the tools you mentioned:

 - [Ollama](https://github.com/ollama/ollama) is interesting as it is one of only a few applications I am aware of that has direct usage of the Level Zero API. **Unfortunately the code seems to be GPU-centric, and would require some modification to work against the Intel NPU Level Zero driver.** (It's also not clear to me how the model runs on Level Zero.) Happily, there is already a feature request for Intel NPU support at ollama/ollama#5747, though the requester seems unaware that Ollama could use re-use the existing Level Zero support rather than integrating the higher-level Intel NPU Acceleration Library.

 - [IPEX-LLM](https://github.com/intel-analytics/ipex-llm), has a README that claims it already has some support for the NPU via the Intel NPU Acceleration Library. From what I can tell you would need to run models using the specific directions provided by that project to have them accelerated by the NPU.

Finally, while I will close this issue as Ollama does not support NPUs at this time, and thus this bug is not a defect in the driver or packaging thereof, I will leave comments open. Please report your successes and failures to get the higher-level components of this stack to work on Fedora. I figure if we can collect enough information we can document it as well as learn how to package it.

Best,
Alexander F. Lent

**Comment by xanderlent** [comment]
Good news on this issue:

Ollama with CPU and AMD GPU support has been [officially packaged in Fedora 42](https://packages.fedoraproject.org/pkgs/ollama/ollama/) and higher by the [AI/ML SIG](https://fedoraproject.org/wiki/SIGs/AI-ML).

At the moment, it still doesn't support Intel NPUs and the Intel GPU support may not be packaged, but this is a substantial improvement in the accessibility of these tools from Fedora.

**Comment by mecattaf** [comment]
Hey @xanderlent [Looks like [openvino will also be available in Fedora 42](https://packages.fedoraproject.org/pkgs/openvino/openvino/) which is also great news. F42 will be big for local ai.

I do not think that ollama will be made intel NPU-compatible anytime soon. I have accepted that we may never get native ollama NPU acceleration.

However, thanks to your copr, I recently managed to get local NPU-accelerated whisper transcription (sst) working. [Feel free to check it out and lmk your thoughts!](https://github.com/mecattaf/whisper-npu-server)

**Comment by xanderlent** [comment]
Thanks! It looks like we will have NPU plugin support in OpenVINO in F42+, and the Fedora AI/ML SIG - which I'm beginning to work with to upstream this - is targeting a broader upstreaming of Intel/AMD/etc. NPU components for F43.

As for ollama, I think it's possible to write an Intel (or other) NPU backend, I just don't have the background in AI (or that codebase) or the time to do so.

Also, thanks for the example! One important note when you are passing the device file through to a driver running in a container, like in your linked example: The Intel folks claim that the driver version and firmware version are tightly coupled and so **you should make sure that the firmware version from this repo matches the driver version you install in the container**.

**Comment by mecattaf** [comment]
@xanderlent I am confused by the instructions you provide specifically: `Install the intel-npu-firmware package.` What repository provides this package? When I search with rpm-ostree, I can see the package exists (intel-npu-firmware : Intel Neural Processing Unit Firmware), but I cannot determine which repository it comes from. Your Copr seems to only provide `intel-npu-level-zero` and `oneapi-level-zero` packages. Could you clarify where I should obtain the firmware package from?

**Comment by xanderlent** [comment]
This repo/my copr provides the `intel-npu-firmware` package.

The `intel-npu-level-zero.spec` specfile [has an extra section defining a package with a different name for the firmware](https://github.com/xanderlent/intel-npu-driver-rpm/blob/b4cd6882379ad4ce14e677d74dc8b358454c87ea/intel-npu-level-zero.spec#L61).

You can also see it as an output of the build in the [Build Results on copr](https://copr.fedorainfracloud.org/coprs/xanderlent/intel-npu-driver/build/8594100/#:~:text=intel%2Dnpu%2Dfirmware%201.13.0).

**Comment by xanderlent** [comment]
(The `oneapi-level-zero` package is just for Fedora 40 and EPEL10; it's a backport of the version found in Fedora 41 and newer, since the NPU driver needs a newer version than Fedora 40 and EPEL doesn't include it at all.)

**Comment by mecattaf** [comment]
Great news: looks like NPU firmware was merged: https://www.phoronix.com/news/Intel-NPU-Firmware-Upstream
Do we still need to install this package @xanderlent ?

**Comment by xanderlent** [comment]
Oh, that is excellent. I remember watching some discussion upstream about it, I guess they decided that the driver/firmware interface was stable enough.

For now, I'm going to keep the firmware subpackage because this change has yet to make its way into Fedora or the upstream NPU driver project.

Thanks for letting me know about this, I'll look into filing a bug against linux-firmware and proposing changes to move it along once there is a release of linux-firmware with the NPU firmware.

**Comment by mecattaf** [comment]
Thank you for having made your previous work public on Copr! I learned a lot from it.
Looks like F42 is gonna be a big one for AI/ML, with ollama openvino and now npu gaining official support :)

**Comment by xanderlent** [comment]
Good news, someone else in the Fedora community has pushed this upstream. Discontinuing this repo now.
